name: Fetch Telegram Channel Posts

on:
  schedule:
    - cron: "*/30 * * * *" # every 30 minutes
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install telegram fs-extra dotenv

      - name: Fetch Telegram Posts
        env:
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_USERNAME: ${{ secrets.TELEGRAM_CHANNEL_USERNAME }}
        run: node fetch_telegram.js

      - name: Commit & push changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          git add telegram_posts.json
          git commit -m "Auto update Telegram posts [skip ci]" || echo "No new posts"
          git push
